name: Deploy frontend to Azure 

on:
  push:
    branches:
      - master
      - feature/azure-front-workflow

env:
  AZURE_WEBAPP_NAME: "eznamka"    # set this to your application's name
  AZURE_WEBAPP_PACKAGE_PATH: './front-end/'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.x' 
  RESOURCEGROUPNAME: "pa200-mnp"
  LOCATION: "West Europe"
  HOSTINGPLANNAME: "ASP-pa200mnp-84d2"
  APPINSIGHTLOCATION: "West Europe"
  SKU: "B1 Basic"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repo
    - uses: actions/checkout@master

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }} 

    - name: Create env file
      run: |
        touch ./front-end/.env
        echo REACT_APP_CONNECTION_URL=${{ secrets.REACT_APP_CONNECTION_URL  }} >> ./front-end/.env
        cat ./front-end/.env

    # Run nodejs start and publish
    - name: npm install, build, and test
      run: |
        cd front-end
        npm install
        npm build --if-present
        npm test --if-present

    - name: 'Deploy node api'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
